### ISSUE TITLE
Tkinter Screen not fitting three questions --> Stan Hacks 2 Product

### ISSUE THREAD

**Issue by KasinadhuniProgrammer** [KasinadhuniProgrammer/HackTacks#1]
So the problem is, the Tkinter screen is not able to fit three questions, instead it is only fitting two. We have two options, we can either change it to two questions, and the user would have to answer 2/2 questions to move onto the next level. Or, we have to figure out a way to scroll down in Tkinter.

**Comment by ProdigySammy21** [comment]
I'll work on it. It'll become 2/2 questions correct. Thanks for the feedback

**Comment by KasinadhuniProgrammer** [comment]
@ProdigySammy21 you have been assigned to this issue.

**Comment by KasinadhuniProgrammer** [comment]
@ProdigySammy21 I approve of the 2/2 solution but please check with the rest of the team as well. Thanks.

**Comment by ProdigySammy21** [comment]
Bug is fixed. Try it out

**Comment by KasinadhuniProgrammer** [comment]
@ProdigySammy21 thanks.
